import assert from "node:assert/strict";
const origin=process.env.KOALA_TEST_URL||"http://127.0.0.1:5173";
const state=async(source="demo")=>{const r=await fetch(`${origin}/api/state?source=${source}`);assert.equal(r.status,200);return r.json();};
const post=async(action,actionId=crypto.randomUUID(),source="demo")=>{const r=await fetch(`${origin}/api/actions`,{method:"POST",headers:{"Content-Type":"application/json",Origin:origin},body:JSON.stringify({...action,source,actionId})});return {status:r.status,body:await r.json()};};
const initial=await state();assert.equal(initial.source,"demo");assert.equal(initial.integrations.deepseekConfigured,false);
const live=await state("live");assert.equal(live.metrics.guests,0);assert.equal(live.plates.length,0);
const actionId=crypto.randomUUID();assert.equal((await post({action:"simulate"},actionId)).status,200);const next=await state();assert.equal(new Date(next.clock)-new Date(initial.clock),60000);assert.ok(next.metrics.takenG>initial.metrics.takenG);
const duplicate=await post({action:"simulate"},actionId);assert.equal(duplicate.body.duplicate,true);assert.equal((await state()).clock,next.clock);
const advance=await Promise.all([post({action:"simulate"}),post({action:"simulate"}),post({action:"simulate"})]);advance.forEach(r=>assert.equal(r.status,200));const advanced=await state();assert.equal(new Date(advanced.clock)-new Date(next.clock),180000);
const task=advanced.tasks.find(t=>t.status==="pending");assert.ok(task);assert.equal((await post({action:"task",id:task.id,status:"preparing"})).status,200);assert.equal((await post({action:"task",id:task.id,status:"completed"})).status,200);const done=await state();assert.equal(done.tasks.find(t=>t.id===task.id).status,"completed");
const p=done.plates.find(p=>p.weightG>0&&!p.issue);assert.ok(p);assert.equal((await post({action:"waste",plateId:p.id,disposition:"discard",reason:"API smoke test"})).status,200);assert.ok((await state()).metrics.wastedG>done.metrics.wastedG);
assert.equal((await post({action:"simulate"},crypto.randomUUID(),"live")).status,400);
const invalid=await post({action:"dish",id:"beef",batch:-1,target:1,leadMinutes:1,safetyMinutes:1,costPerKg:1,confirmed:true});assert.equal(invalid.status,400);
const rejected=await fetch(`${origin}/api/actions`,{method:"POST",headers:{"Content-Type":"application/json",Origin:"https://unrelated.invalid"},body:JSON.stringify({source:"demo",actionId:crypto.randomUUID(),action:"simulate"})});assert.ok([400,403].includes(rejected.status));
const report=await fetch(`${origin}/api/analysis`,{method:"POST",headers:{"Content-Type":"application/json",Origin:origin},body:JSON.stringify({source:"demo",question:"当前应该补哪些菜"})});assert.equal(report.status,200);const analysis=await report.json();assert.equal(analysis.provider,"rules");assert.match(analysis.answer,/模拟数据/);
const csv=await fetch(`${origin}/api/export?source=demo`);assert.equal(csv.status,200);assert.match(csv.headers.get("content-type"),/text\/csv/);assert.match(await csv.text(),/模拟/);
const noIngest=await fetch(`${origin}/api/ingest`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({events:[]})});assert.equal(noIngest.status,503);
const html=await fetch(origin);assert.equal(html.status,200);assert.match(await html.text(),/红考拉/);
console.log("PASS: 15 API scenarios: persistence, source isolation, clock, replay idempotency, concurrent writes, task execution, waste, invalid input, cross-origin, rules analysis, export, missing integration, HTML.");
